### ISSUE TITLE
[🌱Feat] 찜한 상품 수정

### ISSUE THREAD

**Issue by sujinyang00** [UMC-neoul/NEOUL_SERVER#47]
## 🛠️기능 설명 or 브랜치 생성 목적
 >내가 찜한 상품 목록 응답에 상품 이미지,브랜드 이름, 가격, 할인률 추가
요청 url : /my/like/product/list

## ✅To-do list🗒️
- [x] dto > ProductRes > ProductDetailRes 수정
![image](https://github.com/UMC-neoul/NEOUL_SERVER/assets/68004188/160e7d13-2ca2-4d72-a909-64529959b4fe)

- [x] entity > Product.java 수정
![image](https://github.com/UMC-neoul/NEOUL_SERVER/assets/68004188/4674feaa-b666-4cae-8665-1e5e996f255f)

- [x] ProductService.java 수정
![image](https://github.com/UMC-neoul/NEOUL_SERVER/assets/68004188/ee8c9161-32d2-4504-b698-839ab7e89b71)

![image](https://github.com/UMC-neoul/NEOUL_SERVER/assets/68004188/7e1f799d-3293-402e-a898-762aee6917b9)
수정 완료
